# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eaed5ad920ed8872481dc654e208967451ba1ccddacd3083be4831421b71efeaba3036a7856fff77bb6386cff10ccda8e34ffabad0c407d42d97466b941382d2

test:
  secret_key_base: f6465d2d2d6e5343f0f1d86b469ba2969d6b4b6a43ad94f35a7bf9fcf9287176ad940a26ba375a66be1c60b88f267e601fa6df302a0c4d511492d96bd09a8d64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
